ignore:
  - "tests/*"
  - "docs/*"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto

codecov:
  max_report_age: off

comment:
  layout: "diff, flags, files"   # <-- no leading space
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

flags:
  backend:
    paths:
      - "backend/**"

  frontend:
    paths:
      - "frontend/**"
